name: The Rogue Ensemble
favicon: null
layout_spectrum: 0.16702733072452247
typography_spectrum: 0.50871
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ada8a4'
    - '#070618'
    - '#545764'
    - '#74767a'
    - '#e5e7eb'
  brandStrength: 1
  lightness: 0.6521860724315047
  saturation: 0.7757109317462891
  rhythmicContrast: 0
purpose: []
